services:
  - type: web
    name: second-brain
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/notes
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false # This will be set manually in the Render dashboard
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1